### ISSUE TITLE
Misleading "Sending 8192 bytes" log messages

### ISSUE THREAD

**Issue by l29ah** [troglobit/uftpd#33] opened 2021-02-26 12:47 UTC
On the `debug` log level, uftpd sends only one or two `Sending 8192 bytes` messages, even though it in fact sends much more data over the data connection.

**Comment by troglobit** [comment] 2021-02-26 13:46
OK. Patches welcoome

**Comment by troglobit** [comment] 2021-12-11 10:39
Turns out this is by design, I had completely forgot about it.  The idea was to throttle output to stdout/syslog for large files:
https://github.com/troglobit/uftpd/blob/889d8868b342189d18a24ea8fb62cd74ab4d9f61/src/ftpcmd.c#L1060-L1065

I'm going to close with wontfix on this issue, but any redesign to make this better is of course welcome as a pull request. I have no interest though in changing this myself.

**Closed as completed by troglobit** 2021-12-11 10:39 UTC
Labels: wontfix
